-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.address
(

    CONSTRAINT address_pkey PRIMARY KEY (id_address)
);

CREATE TABLE IF NOT EXISTS public.addresstype
(

    CONSTRAINT addresstype_pkey PRIMARY KEY (nameaddresstype)
);

CREATE TABLE IF NOT EXISTS public.cargotype
(

    CONSTRAINT cargotype_pkey PRIMARY KEY (namecargotype)
);

CREATE TABLE IF NOT EXISTS public.constmultiplier
(

    CONSTRAINT constmultiplier_pkey PRIMARY KEY (nameconstmultiplier)
);

CREATE TABLE IF NOT EXISTS public.customer
(

    CONSTRAINT customer_pkey PRIMARY KEY (id_customer)
);

CREATE TABLE IF NOT EXISTS public.driver
(

    CONSTRAINT driver_pkey PRIMARY KEY (id_driver)
);

CREATE TABLE IF NOT EXISTS public.driverstatus
(

    CONSTRAINT driverstatus_pkey PRIMARY KEY (namedriverstatus)
);

CREATE TABLE IF NOT EXISTS public.fueltype
(

    CONSTRAINT fueltype_pkey PRIMARY KEY (namefuel)
);

CREATE TABLE IF NOT EXISTS public.ordercargo
(

    CONSTRAINT ordercargo_pkey PRIMARY KEY (id_order)
);

CREATE TABLE IF NOT EXISTS public.orderstatus
(

    CONSTRAINT orderstatus_pkey PRIMARY KEY (nameorderstatus)
);

CREATE TABLE IF NOT EXISTS public.paymentmethod
(

    CONSTRAINT paymentmethod_pkey PRIMARY KEY (namepaymentmethod)
);

CREATE TABLE IF NOT EXISTS public.tenttype
(

    CONSTRAINT tenttype_pkey PRIMARY KEY (nametenttype)
);

CREATE TABLE IF NOT EXISTS public.vehicle
(

    CONSTRAINT vehicle_pkey PRIMARY KEY (vehiclenumber)
);

CREATE TABLE IF NOT EXISTS public.vehiclestatus
(

    CONSTRAINT vehiclestatus_pkey PRIMARY KEY (namevehiclestatus)
);

ALTER TABLE IF EXISTS public.address
    ADD CONSTRAINT fk_address_addresstype1 FOREIGN KEY (addresstype_nameaddresstype)
    REFERENCES public.addresstype (nameaddresstype) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.driver
    ADD CONSTRAINT fk_driver_driverstatus1 FOREIGN KEY (driverstatus_namedriverstatus)
    REFERENCES public.driverstatus (namedriverstatus) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.ordercargo
    ADD CONSTRAINT fk_order_address1 FOREIGN KEY (address_id_addressdeparture)
    REFERENCES public.address (id_address) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.ordercargo
    ADD CONSTRAINT fk_order_address2 FOREIGN KEY (address_id_addressdelivery)
    REFERENCES public.address (id_address) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.ordercargo
    ADD CONSTRAINT fk_order_cargotype1 FOREIGN KEY (cargotype_namecargotype)
    REFERENCES public.cargotype (namecargotype) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.ordercargo
    ADD CONSTRAINT fk_order_customer1 FOREIGN KEY (customer_id_customer)
    REFERENCES public.customer (id_customer) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.ordercargo
    ADD CONSTRAINT fk_order_driver1 FOREIGN KEY (driver_id_driver)
    REFERENCES public.driver (id_driver) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.ordercargo
    ADD CONSTRAINT fk_order_orderstatus1 FOREIGN KEY (orderstatus_nameorderstatus)
    REFERENCES public.orderstatus (nameorderstatus) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.ordercargo
    ADD CONSTRAINT fk_order_paymentmethod1 FOREIGN KEY (paymentmethod_namepaymentmethod)
    REFERENCES public.paymentmethod (namepaymentmethod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.ordercargo
    ADD CONSTRAINT fk_order_vehicle1 FOREIGN KEY (vehicle_vehiclenumber)
    REFERENCES public.vehicle (vehiclenumber) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.vehicle
    ADD CONSTRAINT fk_vehicle_fueltype1 FOREIGN KEY (fueltype_namefuel)
    REFERENCES public.fueltype (namefuel) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.vehicle
    ADD CONSTRAINT fk_vehicle_tenttype FOREIGN KEY (tenttype_nametenttype)
    REFERENCES public.tenttype (nametenttype) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.vehicle
    ADD CONSTRAINT fk_vehicle_vehiclestatus FOREIGN KEY (vehiclestatus_namevehiclestatus)
    REFERENCES public.vehiclestatus (namevehiclestatus) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

END;